######## Hardware Configuration #####

[Device level]
Device_Tech = 130
# tech unit: nm
Device_Type = NVM
# device type: now support two kinds: NVM and SRAM
Device_Area = 1.44
# area unit: um^2
Read_Level = 2
#
Read_Voltage = 0,0.15
# read voltage unit: V (Updated based on linear characterization region)
Write_Level = 2
#
Write_Voltage = -1,1
# write voltage unit: V (Updated to match measured ±1V sweep range)
Read_Latency = 3.16
# read latency unit: ns
Write_Latency = 10
# write latency unit: ns
Device_Level = 2
# For SRAM, this parameter should be set to 2
Device_Resistance = 1e6, 1e4
# resistence unit: ohm, from HRS to LRS (Maintained until SET/RESET pulsed states are measured)
Device_Variation = 8.8
# only used for NVM
Device_SAF = 0.0,0.0
# SAF disabled
Read_Energy = 1.12e-15
# energy per bit
Write_Energy = 1.6e-15
# energy per bit

[Crossbar level]
Xbar_Size = 256,256
# (Row, Column)
Subarray_Size = 256
# (Row)
Cell_Type = 1T1R
# cell type option: 1T1R, 0T1R
Transistor_Tech = 130
# transistor technology unit: nm
Wire_Resistance = 10
# wire resistance option: value (unit: ohm) or Default (-1)
Wire_Capacity = -1
# wire capacity option: value (unit: fF) or Default (-1)
Load_Resistance = -1
# load resistance (unit:ohm) or Default (-1)
Area_Calculation = 0
# 0: use device area for computing; 1: use device tech for computing

[Interface level]
DAC_Choice = -1
# DAC choice option: -1: User defined
DAC_Area = 0
# DAC area option: unit um^2
DAC_Precision = 8
# DAC precision option: unit bit
DAC_Power = 0
# DAC power option: unit W
DAC_Sample_Rate = 1
# DAC sample rate option: GSamples/s
ADC_Choice = -1
# ADC choice option: -1: User defined
ADC_Area = 0
# ADC area option: unit um^2
ADC_Precision = 6
# ADC precision option: unit bit
ADC_Power = 0
# ADC power option: unit W
ADC_Sample_Rate = 1
# ADC sample rate option: Samples/s
ADC_Interval_Thres = -1
# ADC sample interval threshold option: unit V
Logic_Op = -1
# -1: not support

[Process element level]
PIM_Type = 0
# 0: analog PIM, 1: digital PIM
Xbar_Polarity = 2
# polarity 1: one xbar for both pos and neg; polarity 2: one pos xbar and one neg xbar
Sub_Position = 0
# 0: analog domain subtraction; 1: digital domain subtraction
Group_Num = 1
# number of crossbar groups
DAC_Num = 128
# number of DAC per subarray
ADC_Num = 128
# number of ADC per subarray
PE_inBuf_Size = 0
PE_inBuf_Area = 0
Tile_outBuf_Size = 0
Tile_outBuf_Area = 0
DFU_Buf_Size = 0
DFU_Buf_Area = 0

[Digital module]
Digital_Frequency = 500
# digital part frequency unit: MHz
Adder_Tech = 45
Adder_Area = 0
Adder_Power = 0
Multiplier_Tech = 45
Multiplier_Area = 0
Multiplier_Power = 0
ShiftReg_Tech = 65
ShiftReg_Area = 0
ShiftReg_Power = 0
Reg_Tech = 45
Reg_Area = 0
Reg_Power = 0
JointModule_Tech = 45
JointModule_Area = 0
JointModule_Power = 0

[Tile level]
PE_Num = 2,2
# number of PEs in each tile (x,y)
Pooling_shape = 3,3
Pooling_unit_num = 64
Pooling_Tech = 65
Pooling_area = 0
Tile_Adder_Num = 0
Tile_Adder_Level = 0
Tile_ShiftReg_Num = 0
Tile_ShiftReg_Level = 0
Inter_Tile_Bandwidth = 20
Intra_Tile_Bandwidth = 1024
Tile_outBuf_Size = 0
Tile_outBuf_Area = 0
DFU_Buf_Size = 0
DFU_Buf_Area = 0

[Architecture level]
Buffer_Choice = 1
# 1: SRAM
Buffer_Technology = 90
Buffer_ReadPower = 0
Buffer_WritePower = 0
Buffer_Bitwidth = 64

LUT_Capacity = 1
LUT_Area = 0
LUT_Power = 0
LUT_Bandwidth = 0
Tile_Connection = 2

Tile_Num = 64,64

########### Algorithm Configuration ################

[Algorithm Configuration]
Weight_Polarity = 1
Simulation_Level = 0
NoC_enable = 0